Adjust dark mode colors
Stage-Whisper/Stage-Whisper pull request #21
Opened 2022-09-26 23:20 UTC by mattahorton

| dark | light |
| ---- | ---- |
| ![CleanShot 2022-09-26 at 18 15 46@2x](https://user-images.githubusercontent.com/5567285/192397086-35e62187-2935-4030-9922-a5f005e7509c.png) | ![CleanShot 2022-09-26 at 18 16 06@2x](https://user-images.githubusercontent.com/5567285/192397088-d74b16bb-bfdb-47ec-b174-888bce4414e2.png) |

This is not very clean code at all, but it does do the job to address #14. If you all want, I'm happy to break this isn't pieces and pass each argument only the necessary options.

It would be nice if Gooey let us declare some of this at the global level and pass it down like CSS, but I don't think that's an option.

2022-09-27 16:57 UTC, harrislapiroff requested changes
Thanks so much @mattahorton! This looks pretty great! One change request from me:

Since there isn't actually overlap between the arguments fed to the `Gooey` decorator and the `gooey_options` dict, I don't think we should reuse the same dict—it could cause confusion when reading the code. Can you put the new field options out into a separate variable, maybe called `FIELD_COLORS_DARK`.

Then in each field you could use `gooey_options=FIELD_COLORS_DARK if IS_DARK else {}`

2022-09-28 03:38 UTC, crazy4pi314 submitted a review, later dismissed
Second @mattahorton, made a code suggestion that I think reflects the option passing to gooey. TYSM!

2022-09-28 03:38 UTC, crazy4pi314 commented on stagewhisper/__main__.py
> +    basic_group = parser.add_argument_group("Basic", gooey_options=APPEARANCE_DARK if IS_DARK else APPEARANCE_LIGHT)
An example of what I think @harrislapiroff suggested:
```suggestion
    basic_group = parser.add_argument_group("Basic", gooey_options=FIELD_COLORS_DARK if IS_DARK else {})
```

2022-09-29 03:27 UTC, harrislapiroff approved these changes
Looks great!

2022-09-29 03:27 UTC, merged

2022-09-29 03:28 UTC, crazy4pi314 commented
🎉 🎉 🎉